# ==========================
# GLANCE configuration file
# ==========================

[io]
GAL_INFO = id.txt

[paths]
SSP_DIR = 
STT_DIR = 
BIN_DIR = 
BAYES_DIR = 

[general]
CORES = 0
NEB_CONT = 1
N_MCS = (100,100)
SPEC_LIM = 8740

[fado]
TEMPS_FD = ['BC03']
LIBS_FD = ['Z4.LT.BC']

[starlight]
TEMPS_SL = ['BC03']
LIBS_SL = ['Z4.LT.BC']
SL_CONF = 'LTG.conf'

[ry]
RY_SSC = ['FADO', 'Starlight']
RY_TCS = [0.031,0.102,0.302,1.02,3.01,5.01,7.01,9.01]

[ppxf]
WR_PPXF = 'F'
TEMPS_PPXF = ['IUS']
LINE_STP = 'sep_tied'
NMOM = 4
GST_STP = 'GST'

[dyn_ppxf]
CHI2_TYPE = 'kinmapchi2'
TODO_PDYN = ['MGE', 'kin_clean', 'config']
HST_FILT = 'F814W'
MGE_M = 0
SINF = 0

[bayes]
TEMP_BAYES = 'IUS'
REGUL = 'SP'
WR_BAYES = ['red']

[orbit_decomp]
OCUT = None
V_SIGMA = 'fit'
ERR_DSBP = True

[sinfoni]
TEMPS_SINF = ['GNIRS']
NMOM_SINF = 4 